name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - feat/add-workflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: ./javascript
      run: npm install

    - name: Run tests
      working-directory: ./javascript
      run: npm test